TP Disk/Overlap seed expansion
cms-L1TK/firmware-hls pull request #280
Opened 2023-07-16 03:04 UTC by jasonfan393

PR adds Disk/overlap (L1D1 L2D1 D1D2 D3D4) seeds to TP. Tested as matching emulation on all TPs. 

Timing fails by HLS csynth estimate but passes on full implementation.

Adds an additional bit into AllStubInnerMemory in disks for negative disk information, written by VMRCM

2023-07-16 14:19 UTC, pwittich commented
@jasonfan393 this fails the gitlab CI on the HLS build for the c simulation. is this expected?

2023-07-16 15:06 UTC, jasonfan393 commented
> @jasonfan393 this fails the gitlab CI on the HLS build for the c simulation. is this expected?

not expected, looks like one of my 'cleanups' to get past the quality check has broken the co-sim somehow, looking at it now

2023-08-01 09:33 UTC, aryd requested changes
Suggest some smaller cleanup before merging. (Also will need to rebaseline.)

2023-08-01 13:42 UTC, jasonfan393 commented on TrackletAlgorithm/TrackletProcessor.h
> +        bool negDisk = false
The idea is to avoid having to put in a negDisk values for non-disk seeds, but I can try to think of a smarter way to handle this?

2023-08-06 15:21 UTC, aryd commented on TrackletAlgorithm/TrackletCalculator_calculate_DXDY.h
> +#include "ap_int.h"
Added comment to state that this is auto generate code that should not be modified.

2023-08-06 15:21 UTC, aryd commented on TrackletAlgorithm/TrackletCalculator_calculate_LXD1.h
> +#include "ap_int.h"
Added comment to state that this is auto generate code that should not be modified.

2023-08-06 15:21 UTC, aryd commented on TrackletAlgorithm/TrackletCalculator_calculate_LXLY.h
> +#if __has_include("../emData/LUTs/TC_L1L2_drinv.tab")
Will leave this as an issue for now.

2023-08-06 15:22 UTC, aryd commented on TrackletAlgorithm/TrackletEngineUnit.h
> +#pragma HLS ARRAY_PARTITION variable=stubptinnerlutnew1_ complete dim=1
I saw there is a comment further down in the code when these arrays are used, but I added a comment here as well.

2023-08-06 15:23 UTC, aryd commented on TrackletAlgorithm/TrackletEngineUnit.h
> + RZBIN ibin__, ibin___;
I was wrong these are indeed used and need to stay.

2023-08-06 15:23 UTC, aryd commented on TrackletAlgorithm/TrackletProcessor.h
> +    typedef ap_int<12> z0;
Nope - this needs to be 12 bits.

2023-08-06 15:24 UTC, aryd commented on TrackletAlgorithm/TrackletProcessor.h
> +    if (rproj[i] < 2048) {
Replaced this and a few other hardcoded numbers with meaning full constants.

2023-08-06 15:24 UTC, aryd commented on TrackletAlgorithm/TrackletProcessor.h
> +  bool valid_z0=abs(*z0) < floatToInt(z0cut, kz0) ;
Introduced constants for the cuts.

2023-08-06 15:24 UTC, aryd commented on TrackletAlgorithm/VMRouterCM.h
> +          allstubinner.setNegDisk(negDisk ? 1 : 0);
Yes, this works. Code changed.

2023-08-07 12:12 UTC, aryd approved these changes
Comments addressed. As far as I'm concerned we can merge.

2023-08-07 13:39 UTC, merged