TrackBuilder fixes
cms-L1TK/firmware-hls pull request #319
Opened 2024-02-20 10:07 UTC by aehart

This PR corresponds to https://github.com/cms-L1TK/project_generation_scripts/pull/58, and just updates the emData/project_generation_scripts submodule.

2024-02-26 16:29 UTC, jasonfan393 commented
Looks like this is failing in the reducedCombinedConfig checks ([here](https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/jobs/36371948)). Any idea what's up with that?

2024-02-29 14:46 UTC, aehart commented
> Looks like this is failing in the reducedCombinedConfig checks ([here](https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/jobs/36371948)). Any idea what's up with that?

Good catch, @jasonfan393. I think this just reflects incompatibilities between https://github.com/cms-L1TK/project_generation_scripts/commit/1b0164f20022d39a13c89d60d86759497d36cdbc, which is what https://github.com/cms-L1TK/project_generation_scripts/pull/58 is now based on, and the current master branch of firmware-hls. In particular, there are types missing from IntegrationTests/common/hdl/tf_pkg.vhd, which you added in #315.

I've rebased this branch onto the branch of #315, so we can check the results of the CI tests, and I've converted this to a draft PR, which should be merged after #315.

2024-03-22 16:35 UTC, jasonfan393 requested changes
Now that [project_generation_scripts 58 ](https://github.com/cms-L1TK/project_generation_scripts/pull/58) is merged, I think the submodule just needs to be updated to point to that master branch. Since this PR is just the submodule update, it's good to go after that

2024-03-25 09:22 UTC, aehart commented
> Now that [project_generation_scripts 58 ](https://github.com/cms-L1TK/project_generation_scripts/pull/58) is merged, I think the submodule just needs to be updated to point to that master branch. Since this PR is just the submodule update, it's good to go after that

Done! Thanks, @jasonfan393.

2024-03-25 16:35 UTC, jasonfan393 approved these changes

2024-03-25 16:35 UTC, merged